sm8250-common: Explicitly set as an non-AB target
* I believe the default will change to AB soon so we
* may as well explicitly set AB_OTA_UPDATER to false
* to avoid that problem down the line.

---

This fixes the following error while building:

AssertionError: META/ab_partitions.txt is required for ab_update.